FROM python:3.12-slim

WORKDIR /app

COPY instances /app/instances/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY testbed /app/testbed/

COPY testbed/api/main.py /app/
COPY docker/entrypoint.sh /app/entrypoint.sh

RUN mkdir -p /var/log && touch /var/log/testbed-api.log && chmod 666 /var/log/testbed-api.log

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]